# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Business
    local_business_type: ''
    org_name: 'fluela solutions'
    description: 'A customer-centered landing page for a IT-security company offering solutions for fulfilling the Cyber Resilience Act'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    button:
      enable: true
      text: "Jetzt Anfragen"
      url: 'mailto:securisk-dk@gmail.com'
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} My Company'

# Localization
locale:
  date_format: '2. January 2006'
  time_format: '15:04'
